version: '3'
services:

  bot_api:
    build: .
    command: bash -c "cd /app/bot_api/
      && alembic upgrade head
      && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports: 
      - "8000:8000" 
    restart: always
    env_file:
      - .env 