"""empty message

Revision ID: 81c0fab5f041
Revises: bb42f90a6ad4
Create Date: 2023-06-03 22:00:02.763076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c0fab5f041'
down_revision = 'bb42f90a6ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'user_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_phone', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
